hotkeys:
  shell: {}
  profile: {}
ssh:
  connections:
    - name: Lokal
      host: 192.168.0.227
      port: 22
      user: moritz
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      group: null
terminal:
  colorScheme: &ref_0
    name: my
    foreground: '#ffffff'
    background: 'rgba(0, 0, 0, 1)'
    cursor: white
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  profile: git-bash
  autoOpen: false
  font: Consolas Regular
  background: colorScheme
  cursorBlink: false
  fontSize: 20
  ligatures: false
  bell: 'off'
  customColorSchemes:
    - *ref_0
appearance:
  theme: Compact
  tabsLocation: top
  opacity: 1
  frame: full
  dock: 'off'
  vibrancy: false
enableWelcomeTab: false
